Level passing
IdeaSeeker/RandomForest pull request #34
Opened 2021-12-05 22:13 UTC by SBOne-Kenobi

2021-12-05 22:59 UTC, IdeaSeeker requested changes

2021-12-05 22:59 UTC, IdeaSeeker commented on RandomForest/scripts/funGetStarCount/funGetStarCount.gml
> +			times = [6, 25, 80]
стоит давать одну звезду при любом времени, иначе как-то нехорошо получается по отношению к игроку

2021-12-05 22:59 UTC, IdeaSeeker commented on RandomForest/scripts/funGetStarCount/funGetStarCount.gml
> +			times = [40, 100, 250]
числа хорошие

2021-12-05 22:59 UTC, IdeaSeeker commented on RandomForest/objects/oPauseMenu/Create_0.gml
> +self.screenshot = noone
`noone` это про объекты, не лучше ли `undefined`?

2021-12-05 23:03 UTC, SBOne-Kenobi commented on RandomForest/objects/oPauseMenu/Create_0.gml
> +self.screenshot = noone
Дак это и есть объект, да и я хз там с undefined траблы были какие-то у меня, поэтому избегаю их

2021-12-06 16:17 UTC, IdeaSeeker approved these changes

2021-12-06 16:28 UTC, IdeaSeeker requested changes
F, esc, F -> abort

2021-12-06 17:23 UTC, IdeaSeeker approved these changes

2021-12-06 17:23 UTC, merged